### ISSUE TITLE
Issue about the args

### ISSUE THREAD

**Issue by XuZikang** [guoyb17/FairQuantize#1]
Hi, I tried to run your code, but I found a missing arg, pre_load, used in pre_train.py. Could you tell me the meaning of this argument? Thank you!

**Comment by guoyb17** [comment]
Thank you for noticing. It was used to load datasets in advance for certain devices, and was missed in pre_train.py.

Btw, it was only a temporary bypass to accelerate some of my work, so I set its default as 0 (not activated). If you do need it, use with caution.
